version: "3"

services:
  redis:
    image: redis:alpine
    networks:
      - redis
  backend:
    build:
      dockerfile: "Dockerfile.dev"
      context: backend
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./backend:/app
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - redis
  frontend:
    build:
      dockerfile: "Dockerfile.dev"
      context: frontend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    tty: true

networks:
  redis:
    driver: bridge